
services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    networks:
      - dwv_net

  sender:
    build: ./sender
    depends_on:
      - backend
    networks:
      - dwv_net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - dwv_net

networks:
  dwv_net:
